# Generated by Django 4.1.7 on 2023-02-21 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ombor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahsulot',
            name='ombot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ombor.ombor'),
        ),
    ]
