# Generated by Django 4.1.7 on 2023-02-21 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ombor', '0002_mahsulot_ombot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mahsulot',
            old_name='ombot',
            new_name='ombor',
        ),
    ]
